### ISSUE TITLE
Bad Message Number

### ISSUE THREAD

**Issue by grossrucker** [zalazdi/laravel-imap#1]
i receive the following error:

[Zalazdi\LaravelImap\Exceptions\GetMessagesFailedException]  
  imap_header(): Bad message number  

After changing 
- Client.php line 97:
  $availableMessages = imap_search($this->connection, $criteria, SE_UID);
  to
  $availableMessages = imap_search($this->connection, $criteria);

and
- Message.php line 146:
  $structure = imap_fetchstructure($this->client->connection, $this->message_no, FT_UID);
  to
  $structure = imap_fetchstructure($this->client->connection, $this->message_no);

it worked

regards
Georg

**Comment by zalazdi** [comment]
I fixed it. Please update library (composer update).
