### ISSUE TITLE
mb_convert_encoding(): Illegal character encoding specified

### ISSUE THREAD

**Issue by urameshibr** [zalazdi/laravel-imap#6]
Hi, can you help me?
Im connecting on gmail and has received this error:

GetMessagesFailedException in Client.php line 119:
mb_convert_encoding(): Illegal character encoding specified

My code:

`
        $client = new Client();

```
    $client->connect();

    $mailboxes = $client->getMailboxes($client);

     $mailbox = new Mailbox($client, '{imap.gmail.com:993/imap/ssl}INBOX','INBOX');

     $ids = $mailbox->getMessages(); // this line is problematic

    return dd($ids);
```

`

How to proceed, my friend?

**Comment by thevirt** [comment]
Created pull request to fix that. Hope author will merge this in.
https://github.com/zalazdi/laravel-imap/pull/8
