### ISSUE TITLE
Documentation would be great.

### ISSUE THREAD

**Issue by fwartner** [zalazdi/laravel-imap#7]
How the (excuse me!) fuck do i make use of this library?!

**Comment by maisn3r** [comment]
Looks like we must find ourselfs :D

**Comment by fwartner** [comment]
Great… Not. ^^

**Comment by truongthinnguyen-zz** [comment]
Hi @fwartner ,

I also have a question like you. And here is the way I did and it worked well.
- Install this package by command 

```
$ composer require zalazdi/laravel-imap
```
- Copy file vendor\zalazdi\laravel-imap\config\imap.php to config\imap.php and then you should change host, username, password, etc.. in that file.
- Copy this line to config\app.php into providers section

```
Zalazdi\LaravelImap\LaravelImapServiceProvider::class,
```
- In your controller should be included this code before call function

```
use Zalazdi\LaravelImap\Client;
use Zalazdi\LaravelImap\Mailbox;

...

$client = new Client();
$client->connect();

$mailboxes = $client->getMailboxes();
foreach($mailboxes as $mailbox) {
        dd($mailbox->getMessages());
}
```

Happy coding.

**Comment by sufian07** [comment]
Thanks @truongthinnguyen for this explanation, it would be appreciated if you can provide example for mailbox configuration.

**Comment by rap2hpoutre** [comment]
Fixed via https://github.com/zalazdi/laravel-imap/pull/14

**Comment by rap2hpoutre** [comment]
@zalazdi this issue could be closed
